local Items = {
    Bombs = {
        Default = {
            Rarity = "Common",
        },
        Ball = {
            Rarity = "Cal",
        }
    },
    Sounds = {
        Default = {
            Rarity = "Common",
        }
    },
    Abilities = {
        Default = {
            Rarity = "Common",
        },
        -- For testing 
        Diddy = {
            Rarity = "SSS Rank",
        }
    },
}

return Items